### ISSUE TITLE
Write-up for installation and for vulnerabilities 

### ISSUE THREAD

**Issue by dugdug36** [AvnerCohen/owasp-hack-flask#1]
Hello thank you for this Flask API.

Do you have Write-up for installation and for vulnerabilities ?
@AvnerCohen

**Comment by AvnerCohen** [comment]
Installation is pretty straight forward. I can add to the readme (`pip install -r requirements.txt` hopefully in a dedicated venv)

As for "Write up" what do you mean exactly?  and what would you like to see ?

**Comment by dugdug36** [comment]
I created /usr/share/dict/words with this file: https://gist.githubusercontent.com/wchargin/8927565/raw/d9783627c731268fb2935a731a618aa8e95cf465/words
Now i seems need sqlite3 database :

File "owasp-hack-flask.py", line 134, in <module>
    seed_db()
  File "owasp-hack-flask.py", line 104, in seed_db
    conn = sqlite3.connect(DB_PATH)
sqlite3.OperationalError: unable to open database file

Write-up of solution, i found this encrypted file of hints. Its enough to resolve challenge ?. I don't see CSRF ?. 

Sorry to ask you this but i plan to make Flask API with vulnerable components and you challenges seems interesting for me without flask API knowledge. 

@AvnerCohen

**Comment by AvnerCohen** [comment]
@dugdug36 should hopefully be fixed now.
See added details starting here - https://github.com/AvnerCohen/owasp-hack-flask#installation
